name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUSKY_SKIP_INSTALL: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: |
          npm ci

      - name: Test
        run: |
          npm run lint
          npm run test

      - name: Build
        run: |
          npm run predeploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
